SELECT NUMERO,
        RTRIM(CEDULA) AS CEDULA,
        RTRIM(NOMBRE) AS NOMBRE, RTRIM(APELLIDOS) AS APELLIDOS,
        E_CIVIL AS ESTADO_CIVIL,
        RTRIM(TEL_RES) AS TELEFONO,
        CEL_RES AS CELULAR,
        TEL_OFIC AS TELEFONO_OFICINA,
        RTRIM(APODO) AS GENERO,
        dbo.fnClarionToSQL(FECHA_ING_TRABAJO) AS FECHA_INGRESO_TRABAJO,
        dbo.fnClarionToSQL(FECHA_CANCELACION) AS FECHA_CANCELACION,
        SUELDO,
        RTRIM(CTA_BANCO) AS CTA_BANCO,
        RTRIM(DIR_1) AS DIRECCION_A,
        RTRIM(DIR_2) AS DIRECCION_B,
        RTRIM(CIUDAD),
        ESTATUSCOOP,
        dbo.fnClarionToSQl(FECHA_ACT) AS FECHA_ACT,
        dbo.fnClarionToSQl(FEC_RES) AS FECHA_RES,
        dbo.fnClarionToSQl(FEC_DES) AS FECHA_DES,
        dbo.fnClarionToSQl(FECHA_SALIDA) AS FECHA_SALIDA,
        MOTIVO_SALIDA
FROM [dbo].[CLIENTES] WHERE CEDULA = '00117910042'


