export function initialValues() {
  return {
    documentId: "",
    firstName: "",
    lastName: "",
    alias: "",
    maritalStatus: "",
    gender: "",
    hasChildrens: false,
    childrensQty: 0,
    phone: "",
    mobile: "",
    email: "",
    location: {
      address: "",
      address2: "",
      country: 0,
      state: 0,
      city: 0,
      postalCode: "",
    },
    employmentInformation: {
      companyName: "",
      sector: "",
      department: "",
      isCareerEmployee: false,
      employmentType: "",
      salary: "",
      employmentCountry: 0,
      employmentState: 0,
      employmentCity: 0,
      employmentAddress: "",
      employmentAddress2: "",
      employmentPhone: "",
      employmentPhoneExt: "",
    },
    beneficiaries: [
      {
        beneficiaryDocumentId: "",
        beneficiaryFirstName: "",
        beneficiaryLastName: "",
        beneficiaryPhone: "",
        beneficiaryMobile: "",
        beneficiaryEmail: "",
        beneficiaryRelationship: "",
        beneficiaryNote: "",
        beneficiaryBirthDate: "",
      },
    ],
    documentIdFront: null,
    documentIdBack: null,
    monthlySavingsAccepted: false,
    monthlySavingsContribution: 0,
    enrollmentPaymentAccepted: false,
    enrollmentPayment: 0,
    termsAndConditionsAccepted: false,
    privacyPolicyAccepted: false,
  };
}
