export function initialValues(
  Cedula,
  NumeroDeSocio,
  Nombres,
  Apellidos,
  Apodo,
  EstadoCivil,
  Direccion1,
  Direccion2,
  Ciudad,
  Provincia,
  Pais,
  CodigoPostal,
  HijosDependientes,
  Telefono,
  Celular,
  Correo,
  SocioDesde,
  LugarDeTrabajo,
  Departamento,
  Sector,
  VinculoLaboral,
  Cargo,
  Salario,
  DireccionTrabajo1,
  DireccionTrabajo2,
  CiudadDondeLabora,
  ProvinciaDondeLabora,
  PaisDondeLabora,
  TelefonoTrabajo,
  Extension,
  FechaDeIngreso,
  TrabajaEnLaMismaInstitucion,
  Grupo,
  EsEmpleadoDeCarrera,
  referenciasPersonales,
  Tipo,
  Monto,
  Plazo,
  Garantias,
  MetodoDesembolso,
  EntidadFinanciera,
  TipoDeCuenta,
  NumeroDeCuenta,
  CedulaDelGarante,
  NombreDelGarante,
  ApellidoDelGarante,
  ApodoDelGarante,
  CorreoDelGarante,
  TelefonoDelGarante,
  CelularDelGarante,
  RelacionConElGarante,
  DireccionDelGarante
) {
  return {
    datosPersonales: {
      Cedula: Cedula || "",
      NumeroDeSocio: NumeroDeSocio || "",
      Nombres: Nombres || "",
      Apellidos: Apellidos || "",
      Apodo: Apodo || "",
      EstadoCivil: EstadoCivil || 0,
      Direccion1: Direccion1 || "",
      Direccion2: Direccion2 || "",
      Ciudad: Ciudad || "",
      Provincia: Provincia || "",
      Pais: Pais || "",
      CodigoPostal: CodigoPostal || "",
      HijosDependientes: HijosDependientes || 0,
      Telefono: Telefono || "",
      Celular: Celular || "",
      Correo: Correo || "",
      SocioDesde: SocioDesde || "",
    },
    datosLaborales: {
      LugarDeTrabajo: LugarDeTrabajo || "",
      Departamento: Departamento || "",
      Sector: Sector || 0,
      VinculoLaboral: VinculoLaboral || 0,
      Cargo: Cargo || "",
      Salario: Salario || 0,
      DireccionTrabajo1: DireccionTrabajo1 || "",
      DireccionTrabajo2: DireccionTrabajo2 || "",
      CiudadDondeLabora: CiudadDondeLabora || "",
      ProvinciaDondeLabora: ProvinciaDondeLabora || "",
      PaisDondeLabora: PaisDondeLabora || "",
      TelefonoTrabajo: TelefonoTrabajo || "",
      Extension: Extension || "",
      FechaDeIngreso: FechaDeIngreso || "",
      TrabajaEnLaMismaInstitucion: TrabajaEnLaMismaInstitucion || false,
    },
    otrosDatosLaborales: {
      Grupo: Grupo || 0,
      EsEmpleadoDeCarrera: EsEmpleadoDeCarrera || false,
    },
    referenciasPersonales: [
      {
        Cedula: referenciasPersonales?.Cedula || "",
        Nombres: referenciasPersonales?.Nombres || "",
        Apellidos: referenciasPersonales?.Apellidos || "",
        Apodo: referenciasPersonales?.Apodo || "",
        Correo: referenciasPersonales?.Correo || "",
        Telefono: referenciasPersonales?.Telefono || "",
        Celular: referenciasPersonales?.Celular || "",
        Relacion: referenciasPersonales?.Relacion || 0,
        Direccion1: referenciasPersonales?.Direccion1 || "",
        Direccion2: referenciasPersonales?.Direccion2 || "",
        Ciudad: referenciasPersonales?.Ciudad || "",
        Provincia: referenciasPersonales?.Provincia || "",
        Pais: referenciasPersonales?.Pais || "",
      },
    ] || [{}],
    datosDelPrestamo: {
      Tipo: Tipo || 0,
      Monto: Monto || 50000,
      Plazo: Plazo || 0,
      Garantias: Garantias || 0,
      MetodoDesembolso: MetodoDesembolso || 0,
    },
    cuentaBancaria: {
      EntidadFinanciera: EntidadFinanciera || 0,
      TipoDeCuenta: TipoDeCuenta || 0,
      NumeroDeCuenta: NumeroDeCuenta || "",
    },
    datosDelGarante: {
      CedulaDelGarante: CedulaDelGarante || "",
      NombreDelGarante: NombreDelGarante || "",
      ApellidoDelGarante: ApellidoDelGarante || "",
      ApodoDelGarante: ApodoDelGarante || "",
      CorreoDelGarante: CorreoDelGarante || "",
      TelefonoDelGarante: TelefonoDelGarante || "",
      CelularDelGarante: CelularDelGarante || "",
      RelacionConElGarante: RelacionConElGarante || 0,
      DireccionDelGarante: DireccionDelGarante || "",
    },
  };
}
